import img1 from "../assest/restaurantImages/img1.jpg";
import img2 from "../assest/restaurantImages/img2.jpg";
import img3 from "../assest/restaurantImages/img3.jpg";
import img4 from "../assest/restaurantImages/img4.jpg";
import img5 from "../assest/restaurantImages/img5.jpg";
import img6 from "../assest/restaurantImages/img6.jpg";
import img7 from "../assest/restaurantImages/img7.jpg";
import img8 from "../assest/restaurantImages/img8.jpg";

export const restaurantData = [
  {
    id: 1,
    name: "Pizza Hut",
    rating: 3.9,
    time: "60-65 mins",
    type: "Pizzas",
    location: "Punawale",
    imageUrl:
      "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/e0839ff574213e6f35b3899ebf1fc597",
    menu: {
      starters: ["Garlic Bread", "Cheese Sticks"],
      lunch: ["Pepperoni Pizza", "Margherita Pizza"],
      dinner: ["BBQ Chicken Pizza", "Veggie Supreme Pizza"],
      beverages: ["Coke", "Pepsi"],
    },
  },
  {
    id: 2,
    name: "Burger King",
    rating: 4.1,
    time: "50-55 mins",
    type: "Burgers",
    location: "Wakad",
    imageUrl: img1,
    menu: {
      starters: ["Chicken Fries", "Mozzarella Sticks"],
      lunch: ["Whopper", "Veggie Burger"],
      dinner: ["Double Cheeseburger", "Chicken Sandwich"],
      beverages: ["Sprite", "Fanta"],
    },
  },
  {
    id: 3,
    name: "Subway",
    rating: 4.2,
    time: "45-50 mins",
    type: "Sandwiches",
    location: "Hinjewadi",
    imageUrl: img2,
    menu: {
      starters: ["Salad Bowl", "Soup"],
      lunch: ["Turkey Sub", "Veggie Delight"],
      dinner: ["Chicken Teriyaki Sub", "Meatball Marinara"],
      beverages: ["Iced Tea", "Lemonade"],
    },
  },
  {
    id: 4,
    name: "Domino's Pizza",
    rating: 4.0,
    time: "55-60 mins",
    type: "Pizzas",
    location: "Baner",
    imageUrl: img3,
    menu: {
      starters: ["Stuffed Cheesy Bread", "Parmesan Bread Bites"],
      lunch: ["Pepperoni Pizza", "Cheese Pizza"],
      dinner: ["Deluxe Pizza", "Hawaiian Pizza"],
      beverages: ["Coke", "Diet Coke"],
    },
  },
  {
    id: 5,
    name: "KFC",
    rating: 4.3,
    time: "40-45 mins",
    type: "Chicken",
    location: "Aundh",
    imageUrl: img4,
    menu: {
      starters: ["Chicken Popcorn", "Hot Wings"],
      lunch: ["Zinger Burger", "Chicken Wrap"],
      dinner: ["Fried Chicken Bucket", "Chicken Rice Bowl"],
      beverages: ["Mountain Dew", "Mirinda"],
    },
  },
  {
    id: 6,
    name: "Starbucks",
    rating: 4.5,
    time: "20-25 mins",
    type: "Coffee",
    location: "Pimple Saudagar",
    imageUrl: img5,
    menu: {
      starters: ["Banana Bread", "Butter Croissant"],
      lunch: ["Chicken Panini", "Veggie Sandwich"],
      dinner: ["Turkey Club Sandwich", "Chicken Salad"],
      beverages: ["Latte", "Cappuccino"],
    },
  },
  {
    id: 7,
    name: "McDonald's",
    rating: 4.1,
    time: "30-35 mins",
    type: "Burgers",
    location: "Chinchwad",
    imageUrl: img6,
    menu: {
      starters: ["Fries", "Apple Pie"],
      lunch: ["Big Mac", "Filet-O-Fish"],
      dinner: ["Chicken McNuggets", "McChicken"],
      beverages: ["Coke", "Sprite"],
    },
  },
  {
    id: 8,
    name: "Taco Bell",
    rating: 4.0,
    time: "45-50 mins",
    type: "Mexican",
    location: "Pimpri",
    imageUrl: img7,
    menu: {
      starters: ["Nachos", "Cheesy Roll"],
      lunch: ["Crunchy Taco", "Bean Burrito"],
      dinner: ["Quesadilla", "Mexican Pizza"],
      beverages: ["Mountain Dew", "Pepsi"],
    },
  },
  {
    id: 9,
    name: "Dunkin' Donuts",
    rating: 4.3,
    time: "25-30 mins",
    type: "Donuts",
    location: "Kothrud",
    imageUrl: img8,
    menu: {
      starters: ["Munchkins", "Hash Browns"],
      lunch: ["Turkey Sausage Flatbread", "Veggie Egg White Sandwich"],
      dinner: ["Grilled Cheese", "Chicken Salad Sandwich"],
      beverages: ["Coffee", "Hot Chocolate"],
    },
  },
  {
    id: 10,
    name: "Panda Express",
    rating: 4.4,
    time: "35-40 mins",
    type: "Chinese",
    location: "Karve Nagar",
    imageUrl: img2,
    menu: {
      starters: ["Egg Rolls", "Crab Rangoon"],
      lunch: ["Orange Chicken", "Beef and Broccoli"],
      dinner: ["Kung Pao Chicken", "SweetFire Chicken Breast"],
      beverages: ["Green Tea", "Soda"],
    },
  },
  {
    id: 11,
    name: "Dunkin' Donuts",
    rating: 4.3,
    time: "25-30 mins",
    type: "Donuts",
    location: "Kothrud",
    imageUrl: img4,
    menu: {
      starters: ["Munchkins", "Hash Browns"],
      lunch: ["Turkey Sausage Flatbread", "Veggie Egg White Sandwich"],
      dinner: ["Grilled Cheese", "Chicken Salad Sandwich"],
      beverages: ["Coffee", "Hot Chocolate"],
    },
  },
  {
    id: 12,
    name: "Panda Express",
    rating: 4.4,
    time: "35-40 mins",
    type: "Chinese",
    location: "Karve Nagar",
    imageUrl: img6,
    menu: {
      starters: ["Egg Rolls", "Crab Rangoon"],
      lunch: ["Orange Chicken", "Beef and Broccoli"],
      dinner: ["Kung Pao Chicken", "SweetFire Chicken Breast"],
      beverages: ["Green Tea", "Soda"],
    },
  },
];
